//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.28 at 03:02:15 PM CST 
//


package com.hp.ucmdb.uddoctor.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="desc" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fileName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="keyword" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="lineShiftUp" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="lineShiftDown" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "LogMarker")
public class LogMarker {

    @XmlAttribute(name = "id", required = true)
    protected int id;
    @XmlAttribute(name = "desc", required = true)
    protected String desc;
    @XmlAttribute(name = "fileName", required = true)
    protected String fileName;
    @XmlAttribute(name = "keyword", required = true)
    protected String keyword;
    @XmlAttribute(name = "lineShiftUp", required = true)
    protected int lineShiftUp;
    @XmlAttribute(name = "lineShiftDown", required = true)
    protected int lineShiftDown;

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the desc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesc() {
        return desc;
    }

    /**
     * Sets the value of the desc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesc(String value) {
        this.desc = value;
    }

    /**
     * Gets the value of the fileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * Sets the value of the fileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileName(String value) {
        this.fileName = value;
    }

    /**
     * Gets the value of the keyword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * Sets the value of the keyword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyword(String value) {
        this.keyword = value;
    }

    /**
     * Gets the value of the lineShiftUp property.
     * 
     */
    public int getLineShiftUp() {
        return lineShiftUp;
    }

    /**
     * Sets the value of the lineShiftUp property.
     * 
     */
    public void setLineShiftUp(int value) {
        this.lineShiftUp = value;
    }

    /**
     * Gets the value of the lineShiftDown property.
     * 
     */
    public int getLineShiftDown() {
        return lineShiftDown;
    }

    /**
     * Sets the value of the lineShiftDown property.
     * 
     */
    public void setLineShiftDown(int value) {
        this.lineShiftDown = value;
    }

}
