//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.28 at 03:02:15 PM CST 
//


package com.hp.ucmdb.uddoctor.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Log"/>
 *         &lt;element ref="{}ProblemList"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "log",
    "problemList"
})
@XmlRootElement(name = "root")
public class Root {

    @XmlElement(name = "Log", required = true)
    protected Log log;
    @XmlElement(name = "ProblemList", required = true)
    protected ProblemList problemList;

    /**
     * Gets the value of the log property.
     * 
     * @return
     *     possible object is
     *     {@link Log }
     *     
     */
    public Log getLog() {
        return log;
    }

    /**
     * Sets the value of the log property.
     * 
     * @param value
     *     allowed object is
     *     {@link Log }
     *     
     */
    public void setLog(Log value) {
        this.log = value;
    }

    /**
     * Gets the value of the problemList property.
     * 
     * @return
     *     possible object is
     *     {@link ProblemList }
     *     
     */
    public ProblemList getProblemList() {
        return problemList;
    }

    /**
     * Sets the value of the problemList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProblemList }
     *     
     */
    public void setProblemList(ProblemList value) {
        this.problemList = value;
    }

}
